### ISSUE TITLE
Link back to demo repo to explain what this is

### ISSUE THREAD

**Issue by karlhorky** [css-components/styled-components#4]
Hey, this is looking pretty awesome. What do you think about linking back to the [demo repo](https://github.com/geelen/css-components-demo) for people looking for more info as to what this is?

**Comment by mxstbr** [comment]
This isn't even nearly done or anything, we're still experimenting, which is also why there's no docs. (for now)

We'll definitely do once we're getting somewhere!

**Comment by karlhorky** [comment]
Right, I know it's WIP, I just mean for people who maybe could contribute in the meantime 😉 . I've opened #9 for this. Feel free to close that as well.
