### ISSUE TITLE
Media queries

### ISSUE THREAD

**Issue by mxstbr** [css-components/styled-components#5]
Media queries should not require a user to understand partial imports and `css`. This should work out of the box:

```JS
const Component = styled.div`
  display: block;
  @media (max-width: 500px) {
    display: inline-block;
  }
`;
```

**Comment by jacobpdq** [comment]
Perhaps this is due to the template literals' failure to forward the scope?

**Comment by philpl** [comment]
@jacobpdq not sure what you're referring to. Please refrain from commenting on old issues, especially closed ones :wink:

**Comment by jacobpdq** [comment]
Apologies– I'll open a new issue.
