### ISSUE TITLE
Overriding

### ISSUE THREAD

**Issue by mxstbr** [css-components/styled-components#8]
For some reason I thought this would work:

```JS
const Block = styled.div`
  background-color: blue;
  color: white;
`;

// Override Block and give it a red background, using all other styles (i.e. just adding another class that overrides the background-color
const EmergencyBlock = styled(Block)`
  background-color: red;
`;
```

Can we make this work? That would be a great overriding mechanism.

**Comment by mxstbr** [comment]
This works.

**Comment by haikyuu** [comment]
@mxstbr What about : 
```js
function Block(props){
 return <div></div>
}
```
```js
import Block from '@components'
const styledBlock = styled(Block)`
 background: steelblue;
`
```
 it doesn't work, shouldn't it be working? 😕

**Comment by mxstbr** [comment]
You need to attach the class:

```JS
function Block(props){
 return <div className={props.className}></div>
}
```

`styled-components` injects a class with the given styling. If you don't attach it to a DOM node, you're not attaching it a DOM node, so it can't be in the DOM!

**Comment by haikyuu** [comment]
Thanks. It's [in the docs too.](https://github.com/styled-components/styled-components/blob/master/docs/existing-css.md#using-styled-components-with-existing-css)

**Comment by davibe** [comment]
would it be possible pass the desired className to the styled function ?
i.e.

```jsx
const MyComponent = () => <div className="my-component"> ... </div>
module.exports = styled(component, {className: 'my-component'})`
    ...
`
```

I don't like that my component has to behave (attach the custom className) as `styled` wants it to. I think the component should be agnostic.

**Comment by haikyuu** [comment]
That would make it easy to (automatically) show human-readable classNames in dev mode. It would make chrome inspector more approachable, with classNames extracted from the component names.

**Comment by mxstbr** [comment]
You can pass a class to a styled component and it will work perfectly fine @davibe:

```JS
const MyComp = styled.div`
  some: styles;
`

// ...

<MyComp className="my-global-class" />
```

@haikyuu see #227 and https://github.com/styled-components/babel-transform-styled-components, that will soon be a thing!

**Comment by davibe** [comment]
@mxstbr i know i can pass it a className but that means that the parent component needs to take care of it, which is not what i want either

**Comment by mxstbr** [comment]
Then do this:

```
// MyComp.js
const MyComp = styled.div`
  some: styles;
`

export default => (props) => <MyComp {...props} className="my-global-class" />;
```

Now in your parent component you can just use `MyComp` without having to worry about the class:

```JS
// ParentComp.js
import MyComp from './MyComp.js'

<MyComp />

**Comment by davibe** [comment]
right.

**Comment by davibe** [comment]
@mxstbr just to be clear. If i do it like that the rendered component will have BOTH the class i specified and the one generated by styled, right ?

**Comment by davibe** [comment]
I have also discovered that if i pass my custom className i can't extend the new component with `styled()` anymore, otherwise i get wrong results.. See the `Note:` in main.js here http://www.webpackbin.com/V1HzUEezf

**Comment by haikyuu** [comment]
@davibe it's working as intended. Here is the non breaking code:
```javascript
const ButtonWithClass = (props) => <Button {...props} className={props.className+" button"}  />
```
[http://www.webpackbin.com/4y64Cy-zz](http://www.webpackbin.com/4y64Cy-zz)

**Comment by davecyen** [comment]
I have the same concern as @davibe. I'm importing a third-party component such as:

`import { AppBar } from 'material-ui';`

and then I would like to override its default styling:

```
const OverrideAppBar = styled(AppBar)`
  border: 1px solid red;
  background-color: red;
`;
```

However, these override rules aren't working.

How can I achieve the override **without** editing code from the imported library, i.e. node_modules/material-ui?

**Comment by mxstbr** [comment]
> How can I achieve the override without editing code from the imported library

You tell the `material-ui` people to attach the `className` to their components. I have no idea why they don't do that, but that means they also don't support `<AppBar className="custom-styling" />`, which is pretty ridiculous.

**Comment by GGAlanSmithee** [comment]
@mxstbr @davecyen I'm not sure how `material-ui` applies their styles, but if they inline them, they would override the ones from `styled-components`, would it not? Have you inspected the DOM in chrome dev tools for example?

**Comment by davecyen** [comment]
@mxstbr thanks for the response and forgive me if I'm not understanding correctly. 

Is this what you are suggesting?

```
import { AppBar } from 'material-ui';

const OverrideAppBar = styled(AppBar)`
  border: 1px solid red;
  background-color: red;
`;

// ...

<OverrideAppBar className="custom-styling" />
```
How then do I set the styles for .custom-styling? `material-ui` does support passing in className as a prop.

**Comment by mxstbr** [comment]
> material-ui does support passing in className as a prop.

Then this works, since all styled-components does is pass in the `className`. See https://github.com/styled-components/styled-components/blob/master/docs/existing-css.md

```JS
const OverrideAppBar = styled(AppBar)`
  border: 1px solid red;
  background-color: red;
`;

```

**Comment by GGAlanSmithee** [comment]
Please let me note again, it seems as `material-ui` adds styles **inline**: ([ref](http://www.material-ui.com/#/customization/styles)).

> The first way to override the style of the components is to use the **_inline-style_** approach.

> The second way to override the style of the components is to use the css-style approach.
> 
> Every component provides a className property. Those properties are always applied to the root element.
> 
> Note that CSS properties defined inline are given priority over those defined in a CSS class. You need to use **_!important_** to take precedence over the inline style.

Please excuse me if I missunderstood something.

**Comment by mxstbr** [comment]
Nope you got that right, so you need to use `!important` just due to the way `material-ui` works:

```JS
const OverrideAppBar = styled(AppBar)`
  border: 1px solid red !important;
  background-color: red !important;
`;
```

**Comment by davecyen** [comment]
Thanks @mxstbr @GGAlanSmithee, `!important` is working as suggested although I was hoping for a different answer. 

Bad on `material-ui` for using inline-styles, but would love to see a future update where `styled-component` is able to work around this.

**Comment by mxstbr** [comment]
> but would love to see a future update where styled-components is able to work around this.

How should we work around this? I wish I could tell you we're going to fix this, but there's nothing we can do 😢 the fault is on `material-ui`s side here 😕

**Comment by davecyen** [comment]
@mxstbr you're right. After some further research, confirmed there's no way to override inline-styles without using `!important`. There's an [ongoing debate](https://github.com/callemall/material-ui/issues/1132) amongst the `material-ui` community about this. Anyways, thanks for the help.

**Comment by coffenbacher** [comment]
Is there a way to automatically apply !important to all styles? This can be useful for making widgets in conjunction with cleanslate.css

**Comment by tpinne** [comment]
I second the question from @coffenbacher . We use `semantic-ui-react` and because their selectors have a higher specifity we need to apply `!important` to every css rule to overwrite the default styles of a specific component.

**Comment by mxstbr** [comment]
This is an extremely old issue that I opened before the library was even officially released, it's really not necessary to notify everyone here.

If you have a question or suggestion please ask it in [the community](https://spectrum.chat/styled-components), if you think you've found a bug please submit an issue here. Thanks!
